---
title: "Dissonance in Contra Dance Tunes"
author: "Jennifer England"
format: html
embed-resources: true
editor: visual
---

```{r}
#| echo: false
#| output: false
# functions needed to run
library(tidyverse)

```

Data for the solfege pitches which are dissonant

```{r}

#since NA values truly do represent a non-occurrence of an event (all of these are events being counted, I'm going to replace all of the NA values with 0)

#function to fill in zeroes
fill_zeroes = function(vec){
  replace_na({{ vec }}, 0)
}

#read in data
solf_dissA=read_csv("A_solf_diss.txt",show_col_types=FALSE)
solf_dissB=read_csv("B_solf_diss.txt",show_col_types=FALSE)


#fill all data that is numeric, since all are numeric except for the tune titles
solf_dissA_zeroes <- solf_dissA |> mutate(
    across(where(is.numeric),fill_zeroes)
    )
solf_dissB_zeroes <- solf_dissB |> mutate(
    across(where(is.numeric),fill_zeroes)
    )


#collapse columns by summing 
solf_dissA_cleaned <- solf_dissA_zeroes |> 
  mutate(mi_e = me + mi) |> 
  mutate(fa_i = fa + fi) |> 
  mutate(la_e = la + le) |> 
  mutate(te_i = te + ti) |> 
  select (Tune_name,do, re, mi_e, fa_i, so, la_e, te_i, Other)

#an alternative:
solf_dissA_cleaned <- solf_dissA_zeroes |> 
  mutate(
    mi_e = me + mi,
    fa_i = fa + fi,
    la_e = la + le,
    te_i = te + ti
  ) |> 
  select (Tune_name, do, re, mi_e, fa_i, so, la_e, te_i, Other)

solf_dissB_cleaned <- solf_dissB_zeroes |> 
  mutate(mi_e = me + mi) |> 
  mutate(fa_i = fa + fi) |> 
  mutate(la_e = la + le) |> 
  mutate(te_i = te + ti) |> 
  select (Tune_name,do, re, mi_e, fa_i, so, la_e, te_i, Other)

#pivot longer, calculate average amount of dissonance on each scale degree
solf_dissA_summary <- pivot_longer(
  solf_dissA_cleaned,
  cols=c("do","re","mi_e","fa_i","so","la_e","te_i","Other"),
  names_to = "solfege",
  values_to = "count"
  ) |> 
  group_by(solfege) |> 
  summarize(
    avg_diss = mean(count)
  )

solf_dissB_summary <- pivot_longer(
  solf_dissB_cleaned,
  cols=c("do","re","mi_e","fa_i","so","la_e","te_i","Other"),
  names_to = "solfege",
  values_to = "count"
  ) |> 
  group_by(solfege) |> 
  summarize(
    avg_diss = mean(count)
  )

ggplot(solf_dissA_summary, aes(x = solfege, y = avg_diss)) +
  geom_col()



```

Do the same process for "all" solfege pitches, including those that are dissonant

```{r}
#read in data
SD_A=read_csv("A_SD_dur.txt", show_col_types=FALSE)

SD_B=read_csv("B_SD_dur.txt", show_col_types=FALSE)


#check for any logical values (where the whole column is blank)
SD_A <- SD_A |> 
  # mutate(Other = as.numeric(Other), `1-` = as.numeric(`1-`))
  mutate(
    across(where(is.logical), as.numeric)
  )

SD_B <- SD_B |> 
  # mutate(Other = as.numeric(Other), `1-` = as.numeric(`1-`))
  mutate(
    across(where(is.logical), as.numeric)
  )


#fill all data that is numeric, since all are numeric except for the tune titles
SD_A_zeroes <- SD_A |> mutate(
    across(where(is.numeric),fill_zeroes)
    )

SD_B_zeroes <- SD_B |> mutate(
    across(where(is.numeric),fill_zeroes)
    )

#collapse columns by summing 
SD_A_cleaned <- SD_A_zeroes |> 
  mutate(
    one = `1` + `1+` + `1-`,
    two = `2` + `2+` + `2-`,
    three = `3` + `3+` + `3-`,
    four = `4` + `4+`,
    five = `5` + `5+` + `5-`,
    six = `6` + `6+` + `6-`,
    seven = `7` + `7-`,
  ) |> 
  select (Tune_name,one, two, three, four, five, six, seven, r, Other)

SD_B_cleaned <- SD_B_zeroes |> 
  mutate(
    one = `1` + `1+` + `1-`,
    two = `2` + `2+` + `2-`,
    three = `3` + `3+` + `3-`,
    four = `4` + `4+`,
    five = `5` + `5+` + `5-`,
    six = `6` + `6+` + `6-`,
    seven = `7` + `7-`,
  ) |> 
  select (Tune_name,one, two, three, four, five, six, seven, r, Other)



#pivot longer, calculate average amount of dissonance on each scale degree
SD_A_summary <- pivot_longer(
  SD_A_cleaned,
  cols=c("one","two","three","four","five","six","seven","r","Other"),
  names_to = "scale_deg",
  values_to = "count"
  ) |> 
  group_by(scale_deg) |> 
  summarize(
    avg_diss = mean(count)
  )

SD_B_summary <- pivot_longer(
  SD_B_cleaned,
  cols=c("one","two","three","four","five","six","seven","r","Other"),
  names_to = "scale_deg",
  values_to = "count"
  ) |> 
  group_by(scale_deg) |> 
  summarize(
    avg_diss = mean(count)
  )


```

Join the two datasets

```{r}
#split the names of each, so I can pair them by the tune name (ignoring the rest of the filename, since it just explains the type of info in the original file)

#function to split, since they'll all have same formats
split_names = function(df, tune_name){
  separate_wider_delim(
    {{ tune_name }},
    delim = ".", 
    names = c("tune_name","krn","content","filetype"),
    too_many = "merge"
  )
}

#split_names(solf_dissA_cleaned,Tune_name)

solf_dissA_join <- solf_dissA_cleaned |> 
  separate_wider_delim(
    Tune_name,
    delim = ".", 
    names = c("tune_name","krn","content","filetype"),
    too_many = "merge"
  )

solf_dissB_join <- solf_dissB_cleaned |> 
  separate_wider_delim(
    Tune_name,
    delim = ".", 
    names = c("tune_name","krn","content","filetype"),
    too_many = "merge"
  )


SD_A_join <- SD_A_cleaned |> 
  separate_wider_delim(
    Tune_name,
    delim = ".", 
    names = c("tune_name","krn","content","filetype"),
    too_many = "merge"
  )


SD_B_join <- SD_B_cleaned |> 
  separate_wider_delim(
    Tune_name,
    delim = ".", 
    names = c("tune_name","krn","content","filetype"),
    too_many = "merge"
  )

SD_diff <- SD_A_join |> 
  inner_join(SD_B_join, by = "tune_name", suffix = c("A","B")) |> 
  mutate(
    SD1_diff = oneA-oneB,
    SD2_diff = twoA-twoB,
    SD3_diff = threeA-threeB,
    SD4_diff = fourA-fourB,
    SD5_diff = fiveA-fiveB,
    SD6_diff = sixA-sixB,
    SD7_diff = sevenA-sevenB,
    SDOther_diff = OtherA-OtherB
  )

diss_diff <- solf_dissA_join |> 
  inner_join(solf_dissB_join, by = "tune_name", suffix = c("A","B")) |> 
  mutate(
    SD1_diss_diff = doA-doB,
    SD2_diss_diff = reA-reB,
    SD3_diss_diff = mi_eA-mi_eB,
    SD4_diss_diff = fa_iA-fa_iB,
    SD5_diss_diff = soA-soB,
    SD6_diss_diff = la_eA-la_eB,
    SD7_diss_diff = te_iA-te_iB,
    SDOther_diss_diff = OtherA-OtherB
  ) |> 
  select(
    tune_name,SD1_diss_diff,SD2_diss_diff,SD3_diss_diff,SD4_diss_diff,SD5_diss_diff,SD6_diss_diff,SD7_diss_diff,SDOther_diss_diff
    )

# summarizes the average differences per solfege for all (not dissonant)
SD_diff_summary <- pivot_longer(
  SD_diff,
  cols=c(
    "SD1_diff","SD2_diff","SD3_diff","SD4_diff","SD5_diff","SD6_diff","SD7_diff","SDOther_diff"
    ),
  names_to = "SD_diff",
  values_to = "count"
  ) |> 
  group_by(SD_diff) |> 
  summarize(
    avg_diss = mean(count)
  )

# summarizes the average differences per solfege for the dissonance
diss_diff_summary <- pivot_longer(
  diss_diff,
  cols=c(
    "SD1_diss_diff","SD2_diss_diff","SD3_diss_diff","SD4_diss_diff","SD5_diss_diff","SD6_diss_diff","SD7_diss_diff","SDOther_diss_diff"
    ),
  names_to = "diss_solfege",
  values_to = "count"
  ) |> 
  group_by(diss_solfege) |> 
  summarize(
    avg_diss = mean(count)
  )

ggplot(diss_diff_summary, aes(x = diss_solfege, y = avg_diss)) +
  geom_col()

ggplot(SD_diff_summary, aes(x = SD_diff, y = avg_diss)) +
  geom_col()


```

```{r}


all_joined <- diss_diff |> 
  left_join(SD_diff, by = join_by(tune_name))


```
